# Generated by Django 3.2.3 on 2021-07-13 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('car', models.CharField(max_length=400, verbose_name='Автомобиль')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('datetime', models.DateTimeField(verbose_name='Время')),
                ('status',
                 models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Услуга оказана')], default='pending', max_length=20,
                                  verbose_name='Статус')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
