# Generated by Django 3.2.3 on 2021-07-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-datetime'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('', 'СТО'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Услуга оказана')], default='pending',
                                   max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
