# Generated by Django 3.2.3 on 2021-07-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20210713_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Услуга оказана')], default='pending', max_length=20,
                                   verbose_name='Статус'),
        ),
    ]
