# Generated by Django 3.2.3 on 2021-07-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0003_alter_staticinformation_options'),
        ('accounts', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Мини-заявка',
                'verbose_name_plural': 'Мини-заявки',
            },
        ),
    ]
