# Generated by Django 3.2.3 on 2021-08-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_shortappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('car', models.CharField(blank=True, max_length=400, null=True, verbose_name='Автомобиль')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN номер')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Заявка на запчасти',
                'verbose_name_plural': 'Заявки на запчасти',
            },
        ),
    ]
