# Generated by Django 3.2.3 on 2021-10-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0006_auto_20210906_2226'),
        ('accounts', '0007_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartappointment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings.branch', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Заказ на звонок',
                'verbose_name_plural': 'Заказы на звонок',
            },
        ),
    ]
