# Generated by Django 3.2.3 on 2021-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_auto_20211006_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='phone',
            field=models.CharField(max_length=26, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sparepartappointment',
            name='phone',
            field=models.CharField(max_length=26, verbose_name='Телефон'),
        ),
    ]
