# Generated by Django 3.2.3 on 2022-10-09 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0007_menuservicesorting'),
        ('accounts', '0010_auto_20211006_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='site_settings.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время, указанные пользователем'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='site_settings.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заявки'),
        ),
        migrations.AlterField(
            model_name='shortappointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='site_settings.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='shortappointment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заявки'),
        ),
        migrations.AlterField(
            model_name='sparepartappointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='site_settings.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='sparepartappointment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заявки'),
        ),
    ]
