# Generated by Django 3.2.3 on 2022-12-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0011_auto_20221009_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания заявки'),
        ),
    ]
