# Generated by Django 3.2.3 on 2024-04-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0007_menuservicesorting'),
        ('accounts', '0012_appointment_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyRepairAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(blank=True, max_length=400, null=True, verbose_name='Автомобиль')),
                ('description', models.TextField(verbose_name='Описание')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=26, verbose_name='Телефон')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заявки')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='site_settings.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Заявка на оценку кузовного ремонта',
                'verbose_name_plural': 'Заявки на оценку кузовного ремонта',
            },
        ),
        migrations.CreateModel(
            name='BodyRepairAppointmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='body_repair_appointments/', verbose_name='Изображение')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bodyrepairappointment', verbose_name='Заявка на кузовной ремонт')),
            ],
        ),
    ]
