# Generated by Django 3.2.3 on 2024-05-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0013_bodyrepairappointment_bodyrepairappointmentimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyrepairappointmentimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='bodyrepairappointmentimage',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.bodyrepairappointment',
                                    verbose_name='Заявка на кузовной ремонт'),
        ),
    ]
