# Generated by Django 3.2.3 on 2021-07-24 05:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=120, null=True, populate_from='name', unique=True, verbose_name='URL тега'),
        ),
    ]
