# Generated by Django 3.2.3 on 2021-10-26 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0002_alter_tag_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
