# Generated by Django 3.2.3 on 2021-07-06 12:40

import autoslug.fields
import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('masters', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок статьи')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL статьи')),
                ('text', models.TextField(verbose_name='Контент')),
                ('short_description', models.CharField(help_text='Заполняется для страницы тегов', max_length=250, verbose_name='Краткое описание (до 250 символов)')),
                ('status', models.CharField(choices=[('editing', 'Редактирование'), ('pending', 'Ожидание'), ('published', 'Опубликовано')], default='editing',
                                            help_text='Отображаться будут только статьи с статусом "Опубликовано"', max_length=30, verbose_name='Статус статьи')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='articles/', verbose_name='Изображение статьи')),
                ('thumbnail',
                 image_cropping.fields.ImageRatioField('image', '800x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения для страницы списка новостей')),
                ('icon_thumbnail',
                 image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения для списка "Последние записи" (100x100)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.master', verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article', verbose_name='Статья')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session', verbose_name='Сессия')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('visible', models.BooleanField(default=True, help_text='Снимите галочку вместо удаления.', verbose_name='Отображение')),
                ('text', models.CharField(max_length=2000, verbose_name='Текст комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article', verbose_name='Комментарий под статьёй')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comment', verbose_name='Ответ на комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-date',),
            },
        ),
    ]
