# Generated by Django 3.2.3 on 2021-07-22 15:20

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '800x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                        size_warning=False, verbose_name='Обрезка изображения для страницы списка новостей (800x360)'),
        ),
    ]
