# Generated by Django 3.2.3 on 2021-07-24 05:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True, verbose_name='URL статьи'),
        ),
    ]
