# Generated by Django 3.2.3 on 2021-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0003_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', max_length=256, upload_to='articles/', verbose_name='Изображение статьи'),
        ),
    ]
