# Generated by Django 3.2.3 on 2021-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0020_product_branches'),
        ('news', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='suitable_products',
            field=models.ManyToManyField(blank=True, to='services.Product', verbose_name='Подходящие услуги'),
        ),
    ]
