# Generated by Django 3.2.3 on 2021-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0020_product_branches'),
        ('news', '0005_article_suitable_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='suitable_sections',
            field=models.ManyToManyField(blank=True, to='services.Section', verbose_name='Подходящие разделы'),
        ),
    ]
