# Generated by Django 3.2.3 on 2021-10-26 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0006_article_suitable_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
