# Generated by Django 3.2.3 on 2021-11-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0005_alter_master_credo'),
        ('news', '0007_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Статья/Новость', 'verbose_name_plural': 'Статьи/Новости'},
        ),
        migrations.AddField(
            model_name='article',
            name='is_news',
            field=models.BooleanField(choices=[(True, 'Новость'), (False, 'Статья (База знаний)')], default=True, verbose_name='Отображать в'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Оставьте поле пустым, чтобы не отображать блок автора', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='masters.master', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(help_text='Статья/Новость, под которой был оставлен комментарий', on_delete=django.db.models.deletion.CASCADE, to='news.article',
                                    verbose_name='Статья/Новость'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article', verbose_name='Статья/Новость'),
        ),
    ]
