# Generated by Django 3.2.3 on 2021-11-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0008_auto_20211101_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_news',
            field=models.BooleanField(choices=[(True, 'Новость'), (False, 'Статья (База знаний)')], default=True, verbose_name='Отображать в'),
        ),
    ]
