# Generated by Django 3.2.3 on 2024-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0009_alter_article_is_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=False, help_text='Снимите галочку вместо удаления.', verbose_name='Отображение'),
        ),
    ]
