# Generated by Django 3.2.3 on 2021-06-17 22:34

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название запчасти(ей)')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='services/spare_parts', verbose_name='Изображение')),
                ('product_thumbnail', image_cropping.fields.ImageRatioField('image', '268x118', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для картинки запчасти на странице услуги/товара')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='services/sections', verbose_name='Изображение')),
                ('title_background', image_cropping.fields.ImageRatioField('image', '1920x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для фона заголовка корневого раздела')),
                ('card_thumbnail', image_cropping.fields.ImageRatioField('image', '455x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью на странице раздела 1 уровня')),
                ('parent_section', models.ForeignKey(blank=True, help_text='Оставьте поле пустым, если данный раздел - корневой', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.section', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара/услуги')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='services/products', verbose_name='Изображение')),
                ('product_thumbnail', image_cropping.fields.ImageRatioField('image', '268x118', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для картинки товара/услуги на странице услуги/товара')),
                ('icon_thumbnail', image_cropping.fields.ImageRatioField('image', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью в списке товаров/услуг')),
                ('time_duration', models.CharField(help_text='Заполняется текстом (пример: "2 часа")', max_length=63, verbose_name='Длительность выполнения')),
                ('price', models.FloatField(verbose_name='Цена за работу')),
                ('spare_parts', models.ManyToManyField(to='services.SparePart', verbose_name='Запчасти')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары/Услуги',
            },
        ),
    ]
