# Generated by Django 3.2.3 on 2021-07-06 12:40

import autoslug.fields
import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models

import apps.cars.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название запчасти')),
                ('url', autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название запчасти"', populate_from='title', unique=True,
                                                      verbose_name='URL раздела')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='services/spare_parts', verbose_name='Изображение')),
                ('product_thumbnail',
                 image_cropping.fields.ImageRatioField('image', '268x118', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения для картинки запчасти на странице услуги/товара (268x118)')),
                ('price', models.FloatField(verbose_name='Цена за запчасть (₽)')),
                ('fixed_price', models.BooleanField(default=False, help_text='Не фикскированная цена будет отображаться как "от 990 руб."', verbose_name='Фиксированная цена')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('url', autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название раздела"', populate_from='title', unique=True,
                                                      validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL раздела')),
                ('title_dative',
                 models.CharField(help_text='\nИспользуется при выведении надписей типа "Другие работы по <b>ремонту двигателя</b>" или "Услуги по <b>ремонту двигателя</b>"\n',
                                  max_length=255, verbose_name='Название раздела в Дательном падеже')),
                ('active',
                 models.BooleanField(default=True, help_text='\nНеактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления\n',
                                     verbose_name='Активно')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(
                    help_text='\nПримеры размещения: - для корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--root-section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>   - для НЕ корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>\n',
                    verbose_name='Содержание')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='services/sections', verbose_name='Изображение')),
                ('thumbnail_1960x600',
                 image_cropping.fields.ImageRatioField('image', '1920x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Для фона заголовка страницы',
                                                       hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения (1920x600)')),
                ('thumbnail_960x585', image_cropping.fields.ImageRatioField('image', '960x585', adapt_rotation=False, allow_fullsize=False, free_crop=False,
                                                                            help_text='\nПримеры размещения: <a target="_blank" href="/static/images/admin-examples/vendor_page_thumbnail.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>\n',
                                                                            hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения (960x585)')),
                ('thumbnail_455x200', image_cropping.fields.ImageRatioField('image', '455x200', adapt_rotation=False, allow_fullsize=False, free_crop=False,
                                                                            help_text='Для превью на странице раздела 1 уровня', hide_image_field=False, size_warning=False,
                                                                            verbose_name='Обрезка изображения (455x200)')),
                ('thumbnail_348x236',
                 image_cropping.fields.ImageRatioField('image', '348x236', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (348x236)')),
                ('thumbnail_268x118',
                 image_cropping.fields.ImageRatioField('image', '268x118', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (268x118)')),
                ('thumbnail_80x80',
                 image_cropping.fields.ImageRatioField('image', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (80x80)')),
                ('parent_section',
                 models.ForeignKey(blank=True, help_text='Оставьте поле пустым, если данный раздел - корневой', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='services.section', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара/услуги')),
                ('url', autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название товара/услуги"', populate_from='title', unique=True,
                                                      verbose_name='URL товара/услуги')),
                ('time_duration', models.CharField(help_text='Заполняется текстом (пример: "2 часа")', max_length=63, verbose_name='Длительность выполнения')),
                ('fixed_price', models.BooleanField(default=False, help_text='Не фикскированная цена будет отображаться как "от 990₽"', verbose_name='Фиксированная цена')),
                ('price', models.FloatField(verbose_name='Цена за работу (₽)')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Содержание страницы')),
                ('active',
                 models.BooleanField(default=True, help_text='\nНеактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления\n',
                                     verbose_name='Активно')),
                ('show_at_homepage', models.BooleanField(default=False, help_text='В блоке услуг/товаров', verbose_name='Отображать на главной')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='services/products', verbose_name='Изображение')),
                ('thumbnail_1960x600',
                 image_cropping.fields.ImageRatioField('image', '1920x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Для фона заголовка страницы',
                                                       hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения (1920x600)')),
                ('thumbnail_960x585',
                 image_cropping.fields.ImageRatioField('image', '960x585', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (960x585)')),
                ('thumbnail_455x200',
                 image_cropping.fields.ImageRatioField('image', '455x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (455x200)')),
                ('thumbnail_348x236',
                 image_cropping.fields.ImageRatioField('image', '348x236', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (348x236)')),
                ('thumbnail_268x118',
                 image_cropping.fields.ImageRatioField('image', '268x118', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (268x118)')),
                ('thumbnail_80x80',
                 image_cropping.fields.ImageRatioField('image', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (80x80)')),
                ('cars', models.ManyToManyField(blank=True, to='cars.Modification', verbose_name='Машины, подходящие под данный товар/услугу')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='services.section', verbose_name='Родительский раздел')),
                ('spare_parts', models.ManyToManyField(blank=True, to='services.SparePart', verbose_name='Запчасти')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары/Услуги',
            },
        ),
    ]
