# Generated by Django 3.2.3 on 2021-07-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, help_text='Выводятся когда пользователь попал на услугу, которая не поддерживается его авто', to='services.Product',
                                         verbose_name='Похожие услуги'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_at_homepage',
            field=models.BooleanField(default=False, help_text='В блоке "Наши услуги"', verbose_name='Отображать на главной'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_at_homepage',
            field=models.BooleanField(default=False, help_text='В блоке "Наши услуги"', verbose_name='Отображать на главной'),
        ),
    ]
