# Generated by Django 3.2.3 on 2021-06-17 23:38

import apps.cars.utils.validators
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Неактивные элементы не отображаются нигде кроме админки. Уберите галочку в этом поле, вместо удаления', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='product',
            name='favourite_text',
            field=models.TextField(blank=True, help_text='Небольшой текст с поддержкой html, который будет отображаться под ценой услуги/товара на главной', null=True, verbose_name='Текст избранной услуги/товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='fixed_price',
            field=models.BooleanField(default=False, help_text='Не фикскированная цена будет отображаться как "от 990 руб."', verbose_name='Фиксированная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='home_page',
            field=models.BooleanField(default=False, verbose_name='Отображать в блоке услуг/товаров на главной'),
        ),
        migrations.AddField(
            model_name='product',
            name='homepage_thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '348x236', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью на главной странице'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_favourite',
            field=models.BooleanField(default=False, help_text='Избранные услуги/товары отображаются в соответствующем блоке на главной странице', verbose_name='Отображать в блоке избранных услуг/товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='services.section', verbose_name='Родительский раздел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=autoslug.fields.AutoSlugField(default='', editable=True, help_text='Заполняется на основе поля "Название товара/услуги"', populate_from='title', unique=True, verbose_name='URL товара/услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True, help_text='Неактивные элементы не отображаются нигде кроме админки. Уберите галочку в этом поле, вместо удаления', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='section',
            name='home_page',
            field=models.BooleanField(default=False, verbose_name='Отображать в блоке услуг/товаров на главной'),
        ),
        migrations.AddField(
            model_name='section',
            name='homepage_thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '348x236', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью на главной странице'),
        ),
        migrations.AddField(
            model_name='section',
            name='url',
            field=autoslug.fields.AutoSlugField(default='', editable=True, help_text='Заполняется на основе поля "Название раздела". Автоматически соединяется с родительскими url.', populate_from='title', unique=True, validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL раздела'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена за запчасть'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(blank=True, help_text='Оставьте поле пустым, если данный раздел - корневой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.section', verbose_name='Родительский раздел'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название запчасти'),
        ),
    ]
