# Generated by Django 3.2.3 on 2021-06-18 12:11

import apps.cars.utils.validators
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carfilter'),
        ('services', '0002_auto_20210617_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(to='cars.Modification', verbose_name='Машины, подходящие под данный товар/услугу'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Содержание страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='fixed_price',
            field=models.BooleanField(default=False, help_text='Не фикскированная цена будет отображаться как "от 990 руб."', verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='section',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название раздела"', populate_from='title', unique=True, validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL раздела'),
        ),
    ]
