# Generated by Django 3.2.3 on 2021-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0002_auto_20210707_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, help_text='Выводятся когда пользователь попал на услугу, которая не поддерживается его авто.',
                                         related_name='_services_product_similar_products_+', to='services.Product', verbose_name='Похожие услуги'),
        ),
    ]
