# Generated by Django 3.2.3 on 2021-07-08 02:53

from django.db import migrations

import apps.services.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0003_alter_product_similar_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=apps.services.utils.fields.OptimizedManyToManyField(blank=True, to='cars.Modification', verbose_name='Машины, подходящие под данный товар/услугу'),
        ),
    ]
