# Generated by Django 3.2.3 on 2021-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210618_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='dative',
            field=models.CharField(blank=True, help_text='Используется при выведении надписей типа "Другие работы по <b>ремонту двигателя</b>"', max_length=255, null=True, verbose_name='Название раздела в Дательном падеже'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Неактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True, help_text='Неактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления', verbose_name='Активно'),
        ),
    ]
