# Generated by Django 3.2.3 on 2021-06-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210618_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='dative',
            new_name='title_dative',
        ),
    ]
