# Generated by Django 3.2.3 on 2021-07-08 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0004_alter_product_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='product_thumbnail',
            new_name='thumbnail_268x118',
        ),
    ]
