# Generated by Django 3.2.3 on 2021-06-18 15:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_dative_section_title_dative'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='url',
            field=autoslug.fields.AutoSlugField(default='', editable=True, help_text='Заполняется на основе поля "Название запчасти"', populate_from='title', unique=True, verbose_name='URL раздела'),
            preserve_default=False,
        ),
    ]
