# Generated by Django 3.2.3 on 2021-07-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0005_rename_product_thumbnail_sparepart_thumbnail_268x118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_duration',
            field=models.CharField(blank=True, help_text='Заполняется текстом (пример: "2 часа")', max_length=63, null=True, verbose_name='Длительность выполнения'),
        ),
    ]
