# Generated by Django 3.2.3 on 2021-06-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carfilter'),
        ('services', '0006_sparepart_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, to='cars.Modification', verbose_name='Машины, подходящие под данный товар/услугу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fixed_price',
            field=models.BooleanField(default=False, help_text='Не фикскированная цена будет отображаться как "от 990₽"', verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена за работу (₽)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, null=True, to='services.SparePart', verbose_name='Запчасти'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.FloatField(verbose_name='Цена за запчасть (₽)'),
        ),
    ]
