# Generated by Django 3.2.3 on 2021-07-24 05:14

import apps.cars.utils.validators
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0006_alter_product_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название товара/услуги"', max_length=120, populate_from='title', unique=True,
                                                verbose_name='URL товара/услуги'),
        ),
        migrations.AlterField(
            model_name='section',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название раздела"', max_length=120, populate_from='title', unique=True,
                                                validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL раздела'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название запчасти"', max_length=120, populate_from='title', unique=True,
                                                verbose_name='URL раздела'),
        ),
    ]
