# Generated by Django 3.2.3 on 2021-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0007_auto_20210724_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', max_length=256, upload_to='services/products', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', max_length=256, upload_to='services/sections', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', max_length=256, upload_to='services/spare_parts', verbose_name='Изображение'),
        ),
    ]
