# Generated by Django 3.2.3 on 2021-07-29 23:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0008_auto_20210728_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название запчасти"', max_length=120, populate_from='title', unique=True,
                                                verbose_name='URL запчасти'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='services_pr_active_93a6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_at_homepage'], name='services_pr_show_at_e17287_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section_id'], name='services_pr_section_e7d46f_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['active', 'parent_section'], name='services_se_active_b0ee9a_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['show_at_homepage'], name='services_se_show_at_0c45c4_idx'),
        ),
    ]
