# Generated by Django 3.2.3 on 2021-06-21 02:08

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carfilter'),
        ('services', '0008_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='vendor_page_thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '960x585', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='\nПримеры размещения: <a target="_blank" href="/static/images/admin-examples/vendor_page_thumbnail.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>\n', hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для страницы марки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='\nНеактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления\n', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, to='cars.Modification', verbose_name='Машины, подходящие под данный товар/услугу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, to='services.SparePart', verbose_name='Запчасти'),
        ),
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True, help_text='\nНеактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления\n', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(default='', help_text='\nПримеры размещения: - для корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--root-section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>   - для НЕ корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>\n', verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='title_background',
            field=image_cropping.fields.ImageRatioField('image', '1920x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для фона заголовка'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_dative',
            field=models.CharField(default='', help_text='\nИспользуется при выведении надписей типа "Другие работы по <b>ремонту двигателя</b>" или "Услуги по <b>ремонту двигателя</b>"\n', max_length=255, verbose_name='Название раздела в Дательном падеже'),
            preserve_default=False,
        ),
    ]
