# Generated by Django 3.2.3 on 2021-08-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0009_auto_20210729_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_robots',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', null=True, verbose_name='Meta robots'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Содержимое тега title. Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200,
                                   verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_robots',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', null=True, verbose_name='Meta robots'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Содержимое тега title. Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200,
                                   verbose_name='Заголовок'),
        ),
    ]
