# Generated by Django 3.2.3 on 2021-06-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210621_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title_dative',
            field=models.CharField(blank=True, help_text='\nИспользуется при выведении надписей типа "Другие работы по <b>ремонту двигателя</b>" или "Услуги по <b>ремонту двигателя</b>"\n', max_length=255, null=True, verbose_name='Название раздела в Дательном падеже'),
        ),
    ]
