# Generated by Django 3.2.3 on 2021-06-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_section_title_dative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title_dative',
            field=models.CharField(default='', help_text='\nИспользуется при выведении надписей типа "Другие работы по <b>ремонту двигателя</b>" или "Услуги по <b>ремонту двигателя</b>"\n', max_length=255, verbose_name='Название раздела в Дательном падеже'),
            preserve_default=False,
        ),
    ]
