# Generated by Django 3.2.3 on 2021-09-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0010_auto_20210829_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_to_original',
            field=models.BooleanField(default=False, help_text='Каноничная ссылка на страницу без ММП фильтра', verbose_name='Каноничная ссылка'),
        ),
    ]
