# Generated by Django 3.2.3 on 2021-09-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0011_product_canonical_to_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_header',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200, verbose_name='Заголовок <h1>'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_header',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200, verbose_name='Заголовок <h1>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200, verbose_name='Заголовок <title>'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200, verbose_name='Заголовок <title>'),
        ),
    ]
