# Generated by Django 3.2.3 on 2021-06-26 22:00

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_section_title_dative'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '268x268', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для картинки товара/услуги на странице автомобиля (ММ и выше)'),
        ),
    ]
