# Generated by Django 3.2.3 on 2021-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0012_auto_20210910_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sorting'], 'verbose_name': 'Товар/Услуга', 'verbose_name_plural': 'Товары/Услуги'},
        ),
        migrations.AddField(
            model_name='product',
            name='sorting',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Сортировка'),
            preserve_default=False,
        ),
    ]
