# Generated by Django 3.2.3 on 2021-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0013_auto_20210917_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sorting'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='section',
            name='sorting',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Сортировка'),
            preserve_default=False,
        ),
    ]
