# Generated by Django 3.2.3 on 2021-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0014_auto_20210917_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='homepage_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание для списка акций главной страницы (до 500 символов)'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_promotions',
            field=models.BooleanField(default=False, verbose_name='Отображать среди баннеров акций'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Поддерживает переменные {{vendor}}, {{model}}, {{year}}, {{modification}}.', verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(
                help_text='\nПримеры размещения: - для корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--root-section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>   - для НЕ корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>.\n Поддерживает переменные {{vendor}}, {{model}}, {{year}}, {{modification}}.',
                verbose_name='Содержание'),
        ),
    ]
