# Generated by Django 3.2.3 on 2021-09-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0015_auto_20210917_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_in_promotions',
            field=models.BooleanField(default=False, help_text='Отображать среди баннеров акций на главной', verbose_name='В акциях'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='\nПримеры размещения: - для корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--root-section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>   - для НЕ корневого раздела: <a target="_blank" href="/static/images/admin-examples/description--section.png" style="font-weight: bold; text-decoration: underline;">Посмотреть</a>.\n Поддерживает переменные {{vendor}}, {{model}}, {{year}}, {{modification}}.',
                                   null=True, verbose_name='Содержание'),
        ),
    ]
