# Generated by Django 3.2.3 on 2021-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0016_auto_20210921_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='canonical_to_original',
            field=models.BooleanField(default=False, help_text='Каноничная ссылка на страницу без ММП фильтра', verbose_name='Каноничная ссылка'),
        ),
    ]
