# Generated by Django 3.2.3 on 2021-10-06 15:50

import apps.services.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0010_vendor_favicon'),
        ('services', '0017_section_canonical_to_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cars',
        ),
        migrations.CreateModel(
            name='CarPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('cars', apps.services.utils.fields.OptimizedManyToManyField(blank=True, to='cars.Modification', verbose_name='')),
            ],
            options={
                'verbose_name': 'Набор машин',
                'verbose_name_plural': 'Наборы машин',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='car_pack',
            field=models.ForeignKey(blank=True, help_text='Выберите набор машин, для которого подходит данный товар/услуга', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='services.carpack', verbose_name='Машины, подходящие под данный товар/услугу'),
        ),
    ]
