# Generated by Django 3.2.3 on 2021-10-07 19:47

import apps.services.utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0010_vendor_favicon'),
        ('services', '0018_auto_20211006_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpack',
            name='cars',
            field=apps.services.utils.fields.OptimizedManyToManyField(blank=True, to='cars.Modification', verbose_name='Машины'),
        ),
    ]
