# Generated by Django 3.2.3 on 2021-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0006_auto_20210906_2226'),
        ('services', '0019_alter_carpack_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(help_text='Филиалы, которые оказывают данную услугу', to='site_settings.Branch', verbose_name='Филиалы'),
        ),
    ]
