# Generated by Django 3.2.3 on 2021-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0020_product_branches'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sorting'], name='services_pr_sorting_a14553_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['sorting'], name='services_se_sorting_5ab1f0_idx'),
        ),
    ]
