# Generated by Django 3.2.3 on 2021-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0021_auto_20211102_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(
                help_text='Поддерживает переменные {{vendor}}, {{model}}, {{year}}, {{modification}}. Поддерживает макрос {% works %}. <b>Внимание!</b> Опечатка в макросе приведёт к ошибке сервера.',
                verbose_name='Содержание страницы'),
        ),
    ]
