# Generated by Django 3.2.3 on 2022-02-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0022_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_sections',
            field=models.ManyToManyField(related_name='nephew_product_set', to='services.Section', verbose_name='Дополнительные родительские разделы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='child_product_set', to='services.section', verbose_name='Родительский раздел'),
        ),
    ]
