# Generated by Django 3.2.3 on 2022-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20220215_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='active',
            field=models.BooleanField(default=True, help_text='\nНеактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления\n',
                                      verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_sections',
            field=models.ManyToManyField(blank=True, related_name='nephew_product_set', to='services.Section', verbose_name='Дополнительные родительские разделы'),
        ),
    ]
