# Generated by Django 3.2.3 on 2025-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0024_auto_20220402_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=6, help_text='Укажите 0, чтобы не выводить', verbose_name='Гарантия'),
        ),
    ]
