# Generated by Django 3.2.3 on 2021-07-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorContent',
            fields=[
                ('title', models.CharField(max_length=60, verbose_name='Описание')),
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Ключ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание блока')),
            ],
            options={
                'verbose_name': 'Блок страницы "О нас"',
                'verbose_name_plural': 'Блоки страницы "О нас"',
            },
        ),
    ]
