# Generated by Django 3.2.3 on 2021-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorPage',
            fields=[
                ('url', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='URL страницы')),
                ('content', models.TextField(verbose_name='Содержимое страницы')),
                ('active',
                 models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления. Неактивные страницы не будут отображаться нигде, кроме админ панели',
                                     verbose_name='Активно')),
                ('meta_title', models.CharField(help_text='Содержимое тега title', max_length=200, verbose_name='Заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('meta_robots', models.TextField(blank=True, null=True, verbose_name='Meta robots')),
            ],
            options={
                'verbose_name': 'Страница с изменяемым контентом',
                'verbose_name_plural': 'Страницы с изменяемым контентом',
            },
        ),
        migrations.AddIndex(
            model_name='editorpage',
            index=models.Index(fields=['active', 'url'], name='editor_page_active_85471f_idx'),
        ),
    ]
