# Generated by Django 3.2.3 on 2021-08-31 09:30

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('editor_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorpage',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='editorpage',
            name='title',
            field=models.CharField(default='', help_text='Так-же является содержимым тега title', max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editorpage',
            name='url',
            field=autoslug.fields.AutoSlugField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='URL страницы'),
        ),
    ]
