# Generated by Django 3.2.3 on 2021-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('editor_pages', '0002_auto_20210831_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Страницы этого раздела админ панели имеют отдельные CEO настройки', null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='editorpage',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Страницы этого раздела админ панели имеют отдельные CEO настройки', null=True, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='editorpage',
            name='meta_robots',
            field=models.TextField(blank=True, help_text='Страницы этого раздела админ панели имеют отдельные CEO настройки', null=True, verbose_name='Meta robots'),
        ),
    ]
