# Generated by Django 3.2.3 on 2021-10-26 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('editor_pages', '0003_auto_20210906_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorpage',
            options={'ordering': ['url'], 'verbose_name': 'Страница с изменяемым контентом', 'verbose_name_plural': 'Страницы с изменяемым контентом'},
        ),
    ]
