# Generated by Django 3.2.3 on 2023-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('editor_pages', '0004_alter_editorpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorpage',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Отображать в меню'),
        ),
    ]
