# Generated by Django 3.2.3 on 2023-05-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('editor_pages', '0005_editorpage_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorpage',
            name='show_in_footer',
            field=models.SmallIntegerField(choices=[(1, 'Не отображать'), (2, 'В разделе "О компании"'), (3, 'В разделе "Доп услуги"')], default=1,
                                           verbose_name='Отображать в футере'),
        ),
    ]
