# Generated by Django 3.2.3 on 2021-06-02 10:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('url', autoslug.fields.AutoSlugField(editable=True, help_text='Год и модификация будут указаны автоматически', populate_from='name', unique=True, verbose_name='URL модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='URL производителя')),
                ('logo', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='vendor_logos', verbose_name='Логотип')),
                ('thumbnail_size', image_cropping.fields.ImageRatioField('image', '512x512', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(max_length=200, verbose_name='Год выпуска')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Года выпуска',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модификации')),
                ('years', models.ManyToManyField(to='cars.Year', verbose_name='Года выпуска')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.vendor', verbose_name='Производитель'),
        ),
    ]
