# Generated by Django 3.2.3 on 2021-07-06 12:40

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.cars.utils.car_filter_mixin
import apps.cars.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('url', autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name',
                                                      validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name', unique=True,
                                                      validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL производителя')),
                ('logo', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='vendor_logos', verbose_name='Логотип')),
                ('active', models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Года выпуска',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модификации')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.year', verbose_name='Года выпуска')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.vendor', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='CarFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Время последнего использования')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.model', verbose_name='Модель')),
                ('modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.modification', verbose_name='Модификация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.vendor', verbose_name='Производитель')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.year', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Сохранённый ММП',
                'verbose_name_plural': 'Сохранённые ММП',
                'ordering': ['-last_used'],
                'get_latest_by': 'last_used',
                'unique_together': {('user', 'vendor', 'model', 'year', 'modification')},
            },
            bases=(models.Model, apps.cars.utils.car_filter_mixin.CarFilterUtilsMixin),
        ),
    ]
