# Generated by Django 3.2.3 on 2021-07-07 15:19

import autoslug.fields
from django.db import migrations

import apps.cars.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name', unique=True,
                                                validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL марки'),
        ),
    ]
