# Generated by Django 3.2.3 on 2021-07-07 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_alter_vendor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vendor', verbose_name='Производитель'),
        ),
    ]
