# Generated by Django 3.2.3 on 2021-06-02 11:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_year_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='years',
        ),
        migrations.AddField(
            model_name='modification',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cars.year', verbose_name='Года выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name', unique=True, verbose_name='URL модели'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='thumbnail_size',
            field=image_cropping.fields.ImageRatioField('logo', '512x512', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name', unique=True, verbose_name='URL производителя'),
        ),
    ]
