# Generated by Django 3.2.3 on 2021-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210602_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='year',
        ),
        migrations.AddField(
            model_name='modification',
            name='year',
            field=models.ManyToManyField(to='cars.Year', verbose_name='Года выпуска'),
        ),
    ]
