# Generated by Django 3.2.3 on 2021-07-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0003_alter_model_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfilter',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.modification', verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vendor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.year', verbose_name='Год'),
        ),
    ]
