# Generated by Django 3.2.3 on 2021-06-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210602_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='year',
        ),
        migrations.AddField(
            model_name='modification',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cars.year', verbose_name='Года выпуска'),
            preserve_default=False,
        ),
    ]
