# Generated by Django 3.2.3 on 2021-07-24 05:14

import apps.cars.utils.validators
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0004_auto_20210707_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', max_length=120, populate_from='name',
                                                validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL модели'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', max_length=120, populate_from='name', unique=True,
                                                validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL марки'),
        ),
    ]
