# Generated by Django 3.2.3 on 2021-06-13 09:30

import apps.cars.utils.validators
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210602_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='model',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name', validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL модели'),
        ),
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.vendor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, help_text='Заполняется на основе поля "Название"', populate_from='name', unique=True, validators=[apps.cars.utils.validators.validate_double_slash_url], verbose_name='URL производителя'),
        ),
    ]
