# Generated by Django 3.2.3 on 2021-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0006_alter_vendor_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carfilter',
            index=models.Index(fields=['last_used'], name='cars_carfil_last_us_ab2067_idx'),
        ),
        migrations.AddIndex(
            model_name='carfilter',
            index=models.Index(fields=['user_id'], name='cars_carfil_user_id_45039c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['active'], name='cars_vendor_active_976f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='year',
            index=models.Index(fields=['year'], name='cars_year_year_4a4886_idx'),
        ),
    ]
