# Generated by Django 3.2.3 on 2021-06-13 09:34

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210613_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='thumbnail_size',
            field=image_cropping.fields.ImageRatioField('logo', '512x512', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для превью'),
        ),
    ]
