# Generated by Django 3.2.3 on 2021-06-16 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_alter_vendor_thumbnail_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Время последнего использования')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.model', verbose_name='Модель')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.modification', verbose_name='Модификация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.vendor', verbose_name='Производитель')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.year', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Сохранённый ММП',
                'verbose_name_plural': 'Сохранённые ММП',
            },
        ),
    ]
