# Generated by Django 3.2.3 on 2021-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0007_auto_20210730_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='full_name',
            field=models.CharField(blank=True, max_length=640, null=True, verbose_name='Полное название автомобиля'),
        ),
    ]
