# Generated by Django 3.2.3 on 2021-06-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfilter',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.modification', verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='carfilter',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.year', verbose_name='Год'),
        ),
    ]
