# Generated by Django 3.2.3 on 2021-09-06 15:37

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0008_modification_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='header_crop',
            field=image_cropping.fields.ImageRatioField('header_image', '1920x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения заголовка (1920x600)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='', verbose_name='Изображение в заголовке'),
        ),
    ]
