# Generated by Django 3.2.3 on 2021-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0009_auto_20210906_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Значок будет отображаться при данной марке в ММП фильтре. Оставьте поле пустым чтобы использовать стандартный значок.',
                                    max_length=256, null=True, upload_to='vendor_favicons', verbose_name='Значок страницы (favicon)'),
        ),
    ]
