# Generated by Django 3.2.3 on 2021-10-16 01:36

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0010_vendor_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='header_crop',
            field=image_cropping.fields.ImageRatioField('header_image', '1920x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None,
                                                        hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения заголовка (1920x600)'),
        ),
        migrations.AddField(
            model_name='model',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения. Оставьте пустым, чтобы использовать изображение марки.', null=True,
                                    upload_to='model_header_images', verbose_name='Изображение в заголовке'),
        ),
    ]
