# Generated by Django 3.2.3 on 2021-10-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0011_auto_20211016_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления', verbose_name='Активно'),
        ),
    ]
