# Generated by Django 3.2.3 on 2021-10-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0012_model_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['active'], name='cars_model_active_b70a89_idx'),
        ),
    ]
