# Generated by Django 3.2.3 on 2021-10-23 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0013_model_cars_model_active_b70a89_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',), 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
    ]
