# Generated by Django 3.2.3 on 2021-11-20 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0015_alter_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ('vendor',), 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
