# Generated by Django 3.2.3 on 2024-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0016_alter_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='year',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления', verbose_name='Активно'),
        ),
    ]
