# Generated by Django 3.2.3 on 2021-07-06 12:40

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
                ('show_at_homepage', models.BooleanField(default=False, verbose_name='Отображать на Главной странице')),
                ('active', models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления. Неактивные мастера не отображаются нигде, кроме админ панели',
                                               verbose_name='Активно')),
                ('credo', models.TextField(verbose_name='Кредо')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='masters', verbose_name='Фото')),
                ('thumbnail',
                 image_cropping.fields.ImageRatioField('image', '350x350', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения (350x350)')),
                ('positions', models.ManyToManyField(blank=True, to='masters.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
