# Generated by Django 3.2.3 on 2021-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0002_alter_master_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название должности'),
        ),
    ]
