# Generated by Django 3.2.3 on 2021-07-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0004_auto_20210727_2345'),
        ('masters', '0003_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.branch', verbose_name='Филиал'),
        ),
    ]
