# Generated by Django 3.2.3 on 2021-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0004_master_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='credo',
            field=models.TextField(blank=True, null=True, verbose_name='Кредо'),
        ),
    ]
