# Generated by Django 3.2.3 on 2025-02-19 02:45

from django.db import migrations


def add_ceo_setting(apps, schema_editor):
    CEOSetting = apps.get_model('site_settings', 'CEOSetting')

    CEOSetting.objects.create(
        title='Наша команда',
        header='Наша команда',
        page='Страница о команде автосервиса',
        key='masters:about',
    )


def remove_ceo_setting(apps, schema_editor):
    # Reverse operation: delete the instance if rollback happens
    CEOSetting = apps.get_model('site_settings', 'CEOSetting')
    CEOSetting.objects.filter(key='masters:about').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0005_alter_master_credo'),
        ('site_settings', '0008_bodyrepairemailreceiver'),
    ]

    operations = [
        migrations.RunPython(add_ceo_setting, reverse_code=remove_ceo_setting)
    ]
