# Generated by Django 3.2.3 on 2021-07-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('site_settings', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Ответ')),
                ('answered', models.BooleanField(default=False, help_text='Неотвеченные вопросы не отображаются нигде, кроме админки', verbose_name='Отвечен')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.branch', verbose_name='Филиал (Отвечающий)')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masters.master', verbose_name='Отвечающий')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
    ]
