# Generated by Django 3.2.3 on 2021-07-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
    ]
