# Generated by Django 3.2.3 on 2021-07-20 00:44

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0002_alter_faqentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название вопроса'),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='url',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title', unique=True, verbose_name='URL вопроса'),
        ),
    ]
