# Generated by Django 3.2.3 on 2021-07-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0003_auto_20210720_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='asking_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта спрашивающего'),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='asking_name',
            field=models.CharField(default='Alex', max_length=128, verbose_name='Имя спрашивающего'),
            preserve_default=False,
        ),
    ]
