# Generated by Django 3.2.3 on 2021-07-20 13:24

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0001_initial'),
        ('tags', '0001_initial'),
        ('site_settings', '0001_initial'),
        ('knowledge_base', '0004_auto_20210720_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.master', verbose_name='Отвечающий'),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название симптома')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL симптома')),
                ('active', models.BooleanField(default=True, help_text='Неотвеченные симптомы не отображаются нигде, кроме админки', verbose_name='Отвечен')),
                ('answer', models.CharField(max_length=2048, verbose_name='Ответ')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.branch', verbose_name='Филиал (Отвечающий)')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.master', verbose_name='Отвечающий')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптомы',
            },
        ),
    ]
