# Generated by Django 3.2.3 on 2021-07-24 05:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0005_auto_20210720_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='url',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=120, null=True, populate_from='title', unique=True, verbose_name='URL вопроса'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True, verbose_name='URL симптома'),
        ),
    ]
