# Generated by Django 3.2.3 on 2021-07-29 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0006_auto_20210724_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqentry',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='branch',
        ),
    ]
