# Generated by Django 3.2.3 on 2021-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0007_auto_20210729_1933'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['answered'], name='knowledge_b_answere_ec6a47_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['active'], name='knowledge_b_active_748fab_idx'),
        ),
    ]
