# Generated by Django 3.2.3 on 2021-10-26 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0008_auto_20210730_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqentry',
            options={'ordering': ['-date'], 'verbose_name': 'Вопрос/Ответ', 'verbose_name_plural': 'Вопросы/Ответы'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-date'], 'verbose_name': 'Симптом', 'verbose_name_plural': 'Симптомы'},
        ),
    ]
