# Generated by Django 3.2.3 on 2024-10-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_text', models.CharField(max_length=200, verbose_name='Статичный текст')),
                ('animated_text', models.CharField(max_length=200, verbose_name='Анимированный текст')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='slides', verbose_name='Фоновое изображение')),
                ('sorting', models.PositiveIntegerField(editable=False, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['sorting'],
            },
        ),
    ]
