# Generated by Django 3.2.3 on 2024-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления', verbose_name='Активно'),
        ),
    ]
