# Generated by Django 3.2.3 on 2021-07-06 12:40

import autoslug.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название акции')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL акции')),
                ('active', models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления. Неактивные акции не отображаются нигде, кроме админ панели',
                                               verbose_name='Активно')),
                ('date', models.DateField(verbose_name='Дата')),
                ('show_at_homepage', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('fixed_price', models.BooleanField(default=False, help_text='Фикс. цена: "990₽", НЕ фикс. цена: "от 990₽"', verbose_name='Фиксированная цена')),
                ('price', models.FloatField(verbose_name='Цена за работу (₽)')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание (до 500 символов)')),
                ('text', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='articles/', verbose_name='Изображение статьи')),
                ('thumbnail',
                 image_cropping.fields.ImageRatioField('image', '800x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения для страницы списка акций')),
                ('icon_thumbnail',
                 image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False,
                                                       size_warning=False, verbose_name='Обрезка изображения для списка "Другие акции" (100x100)')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ('-date',),
            },
        ),
    ]
