# Generated by Django 3.2.3 on 2021-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='promotions/', verbose_name='Изображение акции'),
        ),
    ]
