# Generated by Django 3.2.3 on 2021-07-23 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0003_alter_promotion_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='short_description',
            new_name='homepage_description',
        ),
    ]
