# Generated by Django 3.2.3 on 2021-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0004_rename_short_description_promotion_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(default='', max_length=500, verbose_name='Краткое описание (до 500 символов)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='homepage_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание для главной страницы (до 500 символов)'),
        ),
    ]
