# Generated by Django 3.2.3 on 2021-07-24 05:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0006_auto_20210723_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True, verbose_name='URL категории'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True, verbose_name='URL акции'),
        ),
    ]
