# Generated by Django 3.2.3 on 2021-07-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0007_auto_20210724_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='categories',
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.category', verbose_name='Категория (Тип)'),
        ),
    ]
