# Generated by Django 3.2.3 on 2021-07-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0008_auto_20210727_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sale_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за работу (₽)'),
        ),
    ]
