# Generated by Django 3.2.3 on 2021-07-28 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0009_auto_20210728_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='is_sale',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='sale_amount',
        ),
    ]
