# Generated by Django 3.2.3 on 2021-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0010_auto_20210728_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='fixed_price',
            field=models.BooleanField(default=False, help_text='Фикс. цена: "990₽", НЕ фикс. цена: "от 990₽". Фикс. скидка: "15%", НЕ фикс. скидка: "До 15%"',
                                      verbose_name='Фиксированная цена/скидка'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (₽) / Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='sale',
            field=models.BooleanField(choices=[(True, 'Скидка'), (False, 'Цена')], default=False, verbose_name='Цена/Скидка'),
        ),
    ]
