# Generated by Django 3.2.3 on 2021-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0011_auto_20210728_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', max_length=256, upload_to='promotions/', verbose_name='Изображение акции'),
        ),
    ]
