# Generated by Django 3.2.3 on 2021-08-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0013_auto_20210829_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать маску категории или стандартную маску.', null=True,
                                   verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать маску категории или стандартную маску.', null=True, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='meta_robots',
            field=models.TextField(blank=True, help_text='Оставьте поле пустым чтобы использовать маску категории или стандартную маску.', null=True, verbose_name='Meta robots'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Содержимое тега title. Оставьте поле пустым чтобы использовать маску категории или стандартную маску.', max_length=200,
                                   verbose_name='Заголовок'),
        ),
    ]
