# Generated by Django 3.2.3 on 2021-09-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0014_auto_20210829_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_header',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200, verbose_name='Заголовок <h1>'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='meta_header',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать маску категории или стандартную маску.', max_length=200,
                                   verbose_name='Заголовок <h1>'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать стандартную маску.', max_length=200, verbose_name='Заголовок <title>'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым чтобы использовать маску категории или стандартную маску.', max_length=200,
                                   verbose_name='Заголовок <title>'),
        ),
    ]
