# Generated by Django 3.2.3 on 2021-10-26 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0015_auto_20210910_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
