# Generated by Django 3.2.3 on 2021-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0009_alter_article_is_news'),
        ('services', '0021_auto_20211102_2116'),
        ('promotions', '0016_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='articles',
            field=models.ManyToManyField(blank=True, to='news.Article', verbose_name='Привязанные статьи'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, to='services.Product', verbose_name='Привязанные услуги'),
        ),
    ]
