# Generated by Django 3.2.3 on 2022-12-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0007_menuservicesorting'),
        ('promotions', '0017_auto_20211113_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='specific_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.branch', verbose_name='Только конкретный филиал'),
        ),
    ]
