# Generated by Django 3.2.3 on 2023-07-24 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0007_menuservicesorting'),
        ('promotions', '0018_promotion_specific_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='absolute_url',
            field=models.CharField(blank=True, max_length=2083, null=True, verbose_name='Абсолютный URL'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='specific_branch',
            field=models.ForeignKey(blank=True, help_text='Если выбран филиал - пользователю не будет предоставлен выбор, а заявка автоматически отправится в выбранный филиал',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.branch', verbose_name='Только конкретный филиал'),
        ),
    ]
