# Generated by Django 3.2.3 on 2024-04-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0019_auto_20230724_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='absolute_url',
            field=models.CharField(blank=True, help_text='Если заполнить это поле, оно будет использоваться вместо поля "URL акции"', max_length=2083, null=True,
                                   verbose_name='Абсолютный URL'),
        ),
    ]
