# Generated by Django 3.2.3 on 2024-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0020_alter_promotion_absolute_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='active_before',
            field=models.DateField(blank=True, null=True, verbose_name='Активно до'),
        ),
    ]
