# Generated by Django 3.1.4 on 2021-03-04 22:20

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория статей',
                'verbose_name_plural': 'Категории статей',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('short_text', models.CharField(blank=True, help_text='Информация для превью (необязательно). Оставьте поле пустым, чтобы использовать первые 500 знаков статьи', max_length=500, null=True, verbose_name='Описание')),
                ('short_text_ru', models.CharField(blank=True, help_text='Информация для превью (необязательно). Оставьте поле пустым, чтобы использовать первые 500 знаков статьи', max_length=500, null=True, verbose_name='Описание')),
                ('short_text_uz', models.CharField(blank=True, help_text='Информация для превью (необязательно). Оставьте поле пустым, чтобы использовать первые 500 знаков статьи', max_length=500, null=True, verbose_name='Описание')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 250 знаков статьи', max_length=250, null=True, verbose_name='Описание (мета-тег)')),
                ('meta_description_ru', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 250 знаков статьи', max_length=250, null=True, verbose_name='Описание (мета-тег)')),
                ('meta_description_uz', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 250 знаков статьи', max_length=250, null=True, verbose_name='Описание (мета-тег)')),
                ('text', models.TextField(verbose_name='Контент')),
                ('text_ru', models.TextField(null=True, verbose_name='Контент')),
                ('text_uz', models.TextField(null=True, verbose_name='Контент')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок статьи')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Заголовок статьи')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Заголовок статьи')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL статьи')),
                ('status', models.CharField(choices=[('editing', 'Редактирование'), ('pending', 'Ожидание'), ('published', 'Опубликовано')], default='editing', help_text='Отображаться будут только статьи с состоянием "Опубликовано"', max_length=30, verbose_name='Состояние статьи')),
                ('image', models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='articles/', verbose_name='Изображение статьи')),
                ('thumbnail_size', image_cropping.fields.ImageRatioField('image', '512x288', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения для превью')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.articlecategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date'],
            },
        ),
    ]
