from django.contrib.sitemaps.views import x_robots_tag
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from django.urls import reverse


@x_robots_tag
def index(request, sitemaps, template_name='sitemap_index.xml', content_type='application/xml', sitemap_url_name='django.contrib.sitemaps.views.sitemap'):
    """
        This is exact copy of index view from "django\\contrib\\sitemaps\\views.py", which omits pagination and getting protocol
        of each site (commented lines) to prevent calling items() method of each site (this makes significant overhead
    """
    req_protocol = request.scheme
    req_site = get_current_site(request)

    sites = []  # all sections' sitemap URLs
    for section, site in sitemaps.items():
        # For each section label, add links of all pages of its sitemap
        # (usually generated by the `sitemap` view).
        # omitted # if callable(site):
        # omitted #     site = site()
        # omitted # protocol = req_protocol if site.protocol is None else site.protocol
        protocol = req_protocol
        sitemap_url = reverse(sitemap_url_name, kwargs={'section': section})
        absolute_url = '%s://%s%s' % (protocol, req_site.domain, sitemap_url)
        sites.append(absolute_url)
        # omitted # Add links to all pages of the sitemap.
        # omitted # for page in range(2, site.paginator.num_pages + 1):
        # omitted #     sites.append('%s?p=%s' % (absolute_url, page))

    return TemplateResponse(request, template_name, {'sitemaps': sites}, content_type=content_type)
