# Generated by Django 3.2.3 on 2021-07-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('active',
                 models.BooleanField(default=True, help_text='\nНеактивные элементы не отображаются нигде кроме админ панели. Уберите галочку в этом поле, вместо удаления\n',
                                     verbose_name='Активно')),
                ('address', models.CharField(max_length=240, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Тел. номер')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='CEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Содержимое тега title. Так-же поддерживает переменные.', max_length=200, verbose_name='Заголовок')),
                ('page', models.CharField(max_length=120, verbose_name='Описание страницы')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('variables', models.TextField(blank=True, null=True, verbose_name='Доступные переменные')),
                ('description', models.TextField(blank=True, verbose_name='Meta description')),
                ('keywords', models.TextField(blank=True, verbose_name='Meta keywords')),
                ('robots', models.TextField(blank=True, verbose_name='Meta robots')),
            ],
            options={
                'verbose_name': 'CEO настройка',
                'verbose_name_plural': 'CEO настройки',
            },
        ),
        migrations.CreateModel(
            name='StaticInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('add_to_context', models.BooleanField(default=True, verbose_name='Добавлять в контекст')),
                ('key', models.CharField(max_length=200, verbose_name='Ключ')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Статическая информация',
                'verbose_name_plural': 'Статическая информация',
            },
        ),
        migrations.CreateModel(
            name='EmailReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя получателя')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.branch', verbose_name='Относится к филиалу')),
            ],
            options={
                'verbose_name': 'Эл. почта получателя',
                'verbose_name_plural': 'Эл. почты получателей',
            },
        ),
    ]
