# Generated by Django 3.2.3 on 2021-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceosetting',
            name='page',
            field=models.CharField(max_length=120, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='ceosetting',
            name='title',
            field=models.CharField(blank=True, help_text='Содержимое тега <title>. Так-же поддерживает переменные.', max_length=200, verbose_name='Заголовок'),
        ),
    ]
