# Generated by Django 3.2.3 on 2021-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinformation',
            name='category',
            field=models.CharField(choices=[('socials', 'Соц. сети'), ('advantages', 'Наши преимущества'), ('other_data', 'Другие данные'), ('title', 'Заголовок')],
                                   default='socials', max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
