# Generated by Django 3.2.3 on 2021-07-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=120, verbose_name='Страница')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('variables', models.TextField(blank=True, null=True, verbose_name='Доступные переменные')),
                ('description', models.TextField(blank=True, verbose_name='Meta description')),
                ('keywords', models.TextField(blank=True, verbose_name='Meta keywords')),
                ('robots', models.TextField(blank=True, verbose_name='Meta robots')),
            ],
            options={
                'verbose_name': 'Мета-теги',
                'verbose_name_plural': 'Мета-теги',
            },
        ),
    ]
