# Generated by Django 3.2.3 on 2021-07-08 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0002_auto_20210708_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEOSetting',
        ),
    ]
