# Generated by Django 3.2.3 on 2021-07-26 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0002_staticinformation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticinformation',
            options={'ordering': ['category'], 'verbose_name': 'Статическая информация', 'verbose_name_plural': 'Статическая информация'},
        ),
    ]
