# Generated by Django 3.2.3 on 2021-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_delete_ceosetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('page', models.CharField(max_length=120, verbose_name='Описание страницы')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('variables', models.TextField(blank=True, null=True, verbose_name='Доступные переменные')),
                ('description', models.TextField(blank=True, verbose_name='Meta description')),
                ('keywords', models.TextField(blank=True, verbose_name='Meta keywords')),
                ('robots', models.TextField(blank=True, verbose_name='Meta robots')),
            ],
            options={
                'verbose_name': 'CEO настройка',
                'verbose_name_plural': 'CEO настройки',
            },
        ),
    ]
