# Generated by Django 3.2.3 on 2021-07-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0003_alter_staticinformation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailreceiver',
            name='email',
        ),
        migrations.AddField(
            model_name='emailreceiver',
            name='emails',
            field=models.CharField(default='bydev2001@gmail.com', max_length=512, verbose_name='Эл. почта'),
            preserve_default=False,
        ),
    ]
