# Generated by Django 3.2.3 on 2021-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0004_auto_20210727_2345'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['active'], name='site_settin_active_dd95de_idx'),
        ),
        migrations.AddIndex(
            model_name='staticinformation',
            index=models.Index(fields=['key'], name='site_settin_key_b6e780_idx'),
        ),
    ]
