# Generated by Django 3.2.3 on 2021-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0005_alter_ceosetting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceosetting',
            name='title',
            field=models.CharField(blank=True, help_text='Содержимое тега title. Так-же поддерживает переменные.', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='staticinformation',
            name='value',
            field=models.CharField(blank=True, max_length=500, verbose_name='Значение'),
        ),
    ]
