# Generated by Django 3.2.3 on 2021-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0005_auto_20210730_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceosetting',
            name='header',
            field=models.CharField(blank=True, help_text='Поддерживает переменные.', max_length=200, verbose_name='Заголовок <h1>'),
        ),
        migrations.AlterField(
            model_name='ceosetting',
            name='title',
            field=models.CharField(blank=True, help_text='Поддерживает переменные.', max_length=200, verbose_name='Заголовок <title>'),
        ),
    ]
