# Generated by Django 3.2.3 on 2021-11-02 22:12

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0021_auto_20211102_2116'),
        ('site_settings', '0006_auto_20210906_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuServiceSorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.PositiveIntegerField(default=0, editable=False, verbose_name='Сортировка')),
                ('active', models.BooleanField(default=True, verbose_name='Отображать в меню')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sorting', to='services.product')),
                ('root_section', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.section')),
                ('section', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sorting', to='services.section')),
            ],
            options={
                'verbose_name': 'Раздел/Услуга в меню',
                'verbose_name_plural': 'Разделы/Услуги в меню',
                'ordering': ['sorting'],
            },
        ),
    ]
