# Generated by Django 3.2.3 on 2024-05-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0007_menuservicesorting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyRepairEmailReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя получателя')),
                ('emails', models.CharField(max_length=512, verbose_name='Эл. почта')),
                ('foreign_key',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_repair_emails', to='site_settings.branch', verbose_name='Относится к филиалу')),
            ],
            options={
                'verbose_name': 'Эл. почта получателя малярки',
                'verbose_name_plural': 'Эл. почты получателей малярки',
            },
        ),
    ]
