# Generated by Django 3.2.3 on 2026-02-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_auto_20260208_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Долгота'),
        ),
    ]
