# Generated by Django 3.2.3 on 2021-07-24 06:12

import apps.work_gallery.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название категории')),
                ('url', autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(help_text='Используется внутри аттрибута alt=""', max_length=128, verbose_name='Описание фото')),
                ('image',
                 models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to=apps.work_gallery.models.Image.image_path, verbose_name='Изображение')),
                ('list_thumbnail',
                 image_cropping.fields.ImageRatioField('image', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='Для списка всех работ',
                                                       hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения')),
                ('page_thumbnail', image_cropping.fields.ImageRatioField('image', '1170x780', adapt_rotation=False, allow_fullsize=False, free_crop=False,
                                                                         help_text='Для индивидуальной страницы работы', hide_image_field=False, size_warning=False,
                                                                         verbose_name='Обрезка изображения (1170x780)')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название работы')),
                ('url', autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True, verbose_name='URL работы')),
                ('text', models.TextField(verbose_name='Описание работы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_gallery.category', verbose_name='Категория работы')),
                ('main_image',
                 models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_work', to='work_gallery.image', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_gallery.work', verbose_name='Работа'),
        ),
    ]
