# Generated by Django 3.2.3 on 2021-07-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, help_text='Используется внутри аттрибута alt=""', max_length=128, null=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='work',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_work', to='work_gallery.image',
                                       verbose_name='Главное изображение'),
        ),
    ]
