# Generated by Django 3.2.3 on 2021-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0002_auto_20210724_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, help_text='Используется внутри аттрибута alt=" "', max_length=128, null=True, verbose_name='Описание фото'),
        ),
    ]
