# Generated by Django 3.2.3 on 2021-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0003_auto_20210724_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления. Неактивные категории не отображаются нигде, кроме админ панели',
                                      verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='work',
            name='active',
            field=models.BooleanField(default=True, help_text='Снимите галочку с "Активно" вместо удаления. Неактивные работы не отображаются нигде, кроме админ панели',
                                      verbose_name='Активно'),
        ),
    ]
