# Generated by Django 3.2.3 on 2021-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0004_auto_20210724_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(blank=True, to='work_gallery.Category', verbose_name='Категории работы'),
        ),
    ]
