# Generated by Django 3.2.3 on 2021-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0005_auto_20210724_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='iframe_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на <iframe>'),
        ),
    ]
