# Generated by Django 3.2.3 on 2021-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0006_image_iframe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='iframe_url',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы отображать только изображение', max_length=512, null=True, verbose_name='Ссылка на <iframe>'),
        ),
    ]
