# Generated by Django 3.2.3 on 2021-07-28 16:56

from django.db import migrations, models

import apps.work_gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0007_alter_image_iframe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', max_length=256, upload_to=apps.work_gallery.models.Image.image_path,
                                    verbose_name='Изображение'),
        ),
    ]
