# Generated by Django 3.2.3 on 2021-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['active'], name='work_galler_active_20ba9e_idx'),
        ),
    ]
