# Generated by Django 3.2.3 on 2021-08-29 05:06

import apps.work_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0009_work_work_galler_active_20ba9e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения. Изображения автоматически конвертируются в JPEG формат.', max_length=256,
                                    upload_to=apps.work_gallery.models.Image.image_path, verbose_name='Изображение'),
        ),
    ]
