# Generated by Django 3.2.3 on 2021-10-26 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['id'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
    ]
