# Generated by Django 3.2.3 on 2021-11-17 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0014_alter_vendor_options'),
        ('services', '0021_auto_20211102_2116'),
        ('work_gallery', '0011_alter_work_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model', verbose_name='Привязанная машина'),
        ),
        migrations.AddField(
            model_name='work',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.product', verbose_name='Привязанный Товар/Услуга'),
        ),
    ]
