# Generated by Django 3.2.3 on 2021-11-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0022_alter_product_description'),
        ('cars', '0016_alter_model_options'),
        ('work_gallery', '0012_auto_20211117_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='model',
        ),
        migrations.RemoveField(
            model_name='work',
            name='product',
        ),
        migrations.AddField(
            model_name='work',
            name='products',
            field=models.ManyToManyField(blank=True, to='services.Product', verbose_name='Привязанные Товары/Услуги'),
        ),
        migrations.CreateModel(
            name='VendorModelPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('models', models.ManyToManyField(blank=True, to='cars.Model', verbose_name='Модели')),
            ],
            options={
                'verbose_name': 'Набор машин (Марка+модель)',
                'verbose_name_plural': 'Наборы машин (Марка+модель)',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='model_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_gallery.vendormodelpack',
                                    verbose_name='Привязанный набор моделей'),
        ),
    ]
