# Generated by Django 3.2.3 on 2025-02-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('work_gallery', '0013_auto_20211120_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='main_image',
            field=models.OneToOneField(blank=True, help_text='Добавленные изображения появятся тут после сохранения', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='+', to='work_gallery.image', verbose_name='Основное изображение'),
        ),
    ]
